### ISSUE TITLE
Visits support

### ISSUE THREAD

**Issue by flowdee** [affiliatewp/affiliatewp-add-referral-links#1]
As far as I can see views are not being tracked for external referral links?!

This is absolutely mandatory in my opinion. My affiiliates want to see which ref links work well and which not but without the visits statistics it's impossible to be transparent.

**Comment by sumobi** [comment]
@flowdee Visits are tracked by AffiliateWP out of the box. If a user clicks on an affiliate's referral URL (on your external site perhaps) and lands on your site where AffiliateWP is installed, then the visit is tracked and shown to your affiliate. Affiliates can see visits in the "visits" tab of their affiliate area.

**Comment by flowdee** [comment]
Yeah of course I know. But in fact normally AffiliateWP will track _every_ visit of an affiliate link. Let's say an affiliate link is 10 times visited, the normal AffiliateWP will show 10 visits within the affiliate area.

But when I use "external referral" not all 10 visits will be tracked, only the 1 which clicks on a "Buy" link and returns to the Affiliate WP root page.

And the 9 other visits on the landing page which don't lead to the final "buy" are lost. The affiliate will only see 1 visit = 1 referral in the end in his interface. Isn't it?

You see my point?

**Comment by sumobi** [comment]
@flowdee 

> But in fact normally AffiliateWP will track every visit of an affiliate link. Let's say an affiliate link is 10 times visited, the normal AffiliateWP will show 10 visits within the affiliate area.

Only if 10 different users use the same Affiliate's referral URL will the visit show 10 unique times. If it's the same user, only one visit will be stored (even if they clicked it 10 times) until the cookie is cleared. When the cookies are set again, a new visit will be stored.

> But when I use "external referral" not all 10 visits will be tracked, only the 1 which clicks on a "Buy" link and returns to the Affiliate WP root page.

As per above only 1 visit will be stored until the cookies are deleted.

It sounds like you're experiencing default behaviour. There isn't anything special about the links that the external referral links plugin generates. It would be identical to if you manually pasted the referral URL into the browser.

**Comment by flowdee** [comment]
Okay, but you agree with me, that when using the external referrals and when about 100 visits lead to zero sales (referrals) the affiliate will see exactly 0 visits/referrals in his dashboard. I'm sure you can imagine what he thinks about this not existing numbers, about the affiliate program and how long he would participate?

With the "normal" affiliatewp behaviour he would at least see some visits compared to absolutely nothing. Or am I wrong?

Don't get me wrong, I like your tools. I just want to get it working as best as possible.

**Comment by sumobi** [comment]
@flowdee it definitely should not show 0 visits.  

Can you open up a support ticket so I can take a closer look at your external site with the plugin, AffiliateWP site etc? http://affiliatewp.com/support/

**Comment by flowdee** [comment]
Yesterday I setup a multisite in order to prevent this deficient situation. But thanks anyway :+1:
